# -*- mode: python ; coding: utf-8 -*-
"""
PyInstaller spec for the AEMS Local Bridge Agent.

Builds a single-folder distribution with only the agent's dependencies
(uvicorn, fastapi, pydantic, typer) — excludes Flask, SQLAlchemy,
grading engine, and LLM providers to keep the bundle small.

Usage:
    pyinstaller packaging/aems-agent.spec
"""

import sys
from pathlib import Path

block_cipher = None

# Project root (one level up from this spec file)
PROJECT_ROOT = Path(SPECPATH).parent
SRC_ROOT = PROJECT_ROOT / "src"
if str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))

from aems_agent.icons import ensure_windows_icon

WINDOWS_ICON_PATH = ensure_windows_icon(PROJECT_ROOT / "packaging" / "icon.ico")

a = Analysis(
    # Use the launcher wrapper, not cli.py directly.  PyInstaller invokes
    # the entry script as __main__ and strips the package context, which
    # makes cli.py's `from .config import ...` relative imports fail at
    # startup -- the v0.3.2 release defect.  The launcher imports through
    # the fully-qualified package name so relative imports keep working.
    [str(PROJECT_ROOT / 'packaging' / 'launcher.py')],
    pathex=[str(PROJECT_ROOT / 'src')],
    binaries=[],
    datas=[
        # _version.txt is generated by build.py from pyproject.toml so the
        # bundled agent can report the real version when importlib.metadata
        # is unavailable.
        (
            str(PROJECT_ROOT / 'src' / 'aems_agent' / '_version.txt'),
            'aems_agent',
        ),
        # AEMS brand glyph used by the tray icon renderer (icons.py).
        # Without this entry the bundled tray icon falls back to a missing
        # asset error at first render.
        (
            str(PROJECT_ROOT / 'src' / 'aems_agent' / 'assets' / 'aems-logo-mask.png'),
            'aems_agent/assets',
        ),
    ],
    hiddenimports=[
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'pystray',
        'PIL',
        'PIL.Image',
        'PIL.ImageDraw',
        'PIL.ImageFont',
        # cryptography uses cffi via _cffi_backend at runtime; PyInstaller
        # can't see the dynamic import so we have to declare it.
        '_cffi_backend',
        'cffi',
        # Required by grading_bundle.py (direct) and annotate.py (via aems_pdf_annotator._fitz trampoline).
        'fitz',
        'pymupdf',
        'aems_pdf_annotator',
        'aems_pdf_annotator._fitz',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        # Exclude the full AEMS web app and heavy dependencies
        'flask',
        'flask_login',
        'flask_wtf',
        'sqlalchemy',
        'alembic',
        'redis',
        'celery',
        'anthropic',
        'openai',
        'google.generativeai',
        'ollama',
        'tesseract',
        'pytesseract',
        'playwright',
        'matplotlib',
        'pandas',
        'numpy',
        'scipy',
        'sklearn',
        'torch',
        'tensorflow',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='aems-agent',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    # Avoid UPX-packed binaries for end-user builds. Native PDF/crypto/image
    # dependencies are more reliable unpacked, and AV heuristics are calmer.
    upx=False,
    console=False if sys.platform in {'win32', 'darwin'} else True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=str(WINDOWS_ICON_PATH),
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name='aems-agent',
)
