# -*- mode: python ; coding: utf-8 -*-
"""
PyInstaller spec for the AEMS Local Bridge Agent.

Builds a single-folder distribution with only the agent's dependencies
(uvicorn, fastapi, pydantic, typer) — excludes Flask, SQLAlchemy,
grading engine, and LLM providers to keep the bundle small.

Usage:
    pyinstaller packaging/aems-agent.spec
"""

import sys
from pathlib import Path

block_cipher = None

# Project root (one level up from this spec file)
PROJECT_ROOT = Path(SPECPATH).parent
SRC_ROOT = PROJECT_ROOT / "src"
if str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))

from aems_agent.icons import ensure_windows_icon

WINDOWS_ICON_PATH = ensure_windows_icon(PROJECT_ROOT / "packaging" / "icon.ico")

a = Analysis(
    # Use the launcher wrapper, not cli.py directly.  PyInstaller invokes
    # the entry script as __main__ and strips the package context, which
    # makes cli.py's `from .config import ...` relative imports fail at
    # startup -- the v0.3.2 release defect.  The launcher imports through
    # the fully-qualified package name so relative imports keep working.
    [str(PROJECT_ROOT / 'packaging' / 'launcher.py')],
    pathex=[str(PROJECT_ROOT / 'src')],
    binaries=[],
    datas=[
        # _version.txt is generated by build.py from pyproject.toml so the
        # bundled agent can report the real version when importlib.metadata
        # is unavailable.
        (
            str(PROJECT_ROOT / 'src' / 'aems_agent' / '_version.txt'),
            'aems_agent',
        ),
        # AEMS brand glyph used by the tray icon renderer (icons.py).
        # Without this entry the bundled tray icon falls back to a missing
        # asset error at first render.
        (
            str(PROJECT_ROOT / 'src' / 'aems_agent' / 'assets' / 'aems-logo-mask.png'),
            'aems_agent/assets',
        ),
    ],
    hiddenimports=[
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'pystray',
        'PIL',
        'PIL.Image',
        'PIL.ImageDraw',
        'PIL.ImageFont',
        # cryptography uses cffi via _cffi_backend at runtime; PyInstaller
        # can't see the dynamic import so we have to declare it.
        '_cffi_backend',
        'cffi',
        # Required by grading_bundle.py (direct) and annotate.py (via aems_pdf_annotator._fitz trampoline).
        'fitz',
        'pymupdf',
        'aems_pdf_annotator',
        'aems_pdf_annotator._fitz',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        # Exclude the full AEMS web app and heavy dependencies
        'flask',
        'flask_login',
        'flask_wtf',
        'sqlalchemy',
        'alembic',
        'redis',
        'celery',
        'anthropic',
        'openai',
        'google.generativeai',
        'ollama',
        'tesseract',
        'pytesseract',
        'playwright',
        'matplotlib',
        'pandas',
        'numpy',
        'scipy',
        'sklearn',
        'torch',
        'tensorflow',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='aems-agent',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    # Avoid UPX-packed binaries for end-user builds. Native PDF/crypto/image
    # dependencies are more reliable unpacked, and AV heuristics are calmer.
    upx=False,
    console=False if sys.platform in {'win32', 'darwin'} else True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=str(WINDOWS_ICON_PATH),
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name='aems-agent',
)

# macOS: also produce a proper .app bundle alongside the onedir
# distribution. PyInstaller's BUNDLE directive puts the executable in
# Contents/MacOS/aems-agent and the bundled libraries in
# Contents/Frameworks/, which matches Apple's bundle conventions and
# lets `codesign --deep` walk the tree without choking on PyInstaller's
# pip metadata directories. Without BUNDLE we have to manually assemble
# the .app into Contents/MacOS/_internal/ (Apple's "flat bundle"
# layout), which codesign refuses to sign reliably — the v0.4.11/0.4.12
# CI failures were all variants of "bundle format unrecognized,
# invalid, or unsuitable" stemming from that layout.
if sys.platform == 'darwin':
    # Resolve the icns we generate from the brand glyph so PyInstaller
    # can ship a real multi-resolution icon. The CI workflow / build.py
    # path also generates this; we render here to make the spec usable
    # standalone too.
    from aems_agent.icons import ensure_macos_icns

    _MACOS_ICNS_PATH = PROJECT_ROOT / 'packaging' / 'aems-agent.icns'
    ensure_macos_icns(_MACOS_ICNS_PATH)

    _PYPROJECT = PROJECT_ROOT / 'pyproject.toml'
    if sys.version_info >= (3, 11):
        import tomllib as _tomllib  # type: ignore[no-redef]
    else:
        import tomli as _tomllib  # type: ignore[no-redef]
    with open(_PYPROJECT, 'rb') as _f:
        _pkg_version = _tomllib.load(_f)['project']['version']

    app = BUNDLE(
        coll,
        name='AEMS Agent.app',
        icon=str(_MACOS_ICNS_PATH),
        bundle_identifier='com.aems.agent',
        version=_pkg_version,
        info_plist={
            'CFBundleName': 'AEMS Agent',
            'CFBundleDisplayName': 'AEMS Agent',
            'CFBundleVersion': _pkg_version,
            'CFBundleShortVersionString': _pkg_version,
            'CFBundleExecutable': 'aems-agent',
            'CFBundlePackageType': 'APPL',
            'CFBundleIconFile': 'aems-agent.icns',
            'LSMinimumSystemVersion': '11.0',
            # LSUIElement marks this an "agent" app: no Dock icon, but it
            # CAN own a menu-bar NSStatusBar item (the pystray tray). We
            # must NOT also set LSBackgroundOnly — that declares a pure
            # background daemon which the WindowServer forbids from
            # presenting any UI, including the status-bar item. Setting
            # both suppressed the tray icon, so a Finder double-click ran
            # `run --tray` but the user still saw nothing in the menu bar
            # (the same "double-click does nothing" symptom v0.4.16 set
            # out to fix). LSUIElement alone is the correct menu-bar-app
            # contract.
            'LSUIElement': True,
            'NSHighResolutionCapable': True,
        },
    )
